# Data parameters
data:
  data_dir: 'dataset'
  class_names: ['cat', 'dog']
# device
device: 'cpu'
# Training parameters
training:
  output_folder: output
  resume: False
  nb_epochs: 1
  batch_size: 4
  loss:
    name: CrossEntropyLoss
    weight: [1.0,1.0] ### can be removed
  optimizer:
    name: Adam
    lr: 0.0001
  lr_schedule:
    name: MultiStepLR
    milestones: [2,5]
  pin_memory: False
  num_workers: 4
  transforms:
    Resize:
      size: [224,224]
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
# Saving parameters
saving:
  output_folder: output
  save: all
# Model parameters
model:
  name: mobilenet_v2
  pretrained: True